article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="article"

urlpatterns = [
    path('dashboard', views.dashboard,name="dashboard"),
    path('addarticle', views.addarticle,name="addarticle"),
    path('article/<int:id>', views.detail,name="detail"),
    path('edit/<int:id>', views.editarticle, name="edit"),
    path('delete/<int:id>', views.deletearticle,name="delete"),
    path('', views.articles,name="articles"),
    path('comment/<int:id>', views.addcomment, name="comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

# from article.views import index
from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about', views.about,name="about"),
    # path('detail/<int:id>', views.detail,name="detail"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from turtle import ondrag
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")
    article_image=models.FileField(blank=True,null=True,verbose_name="Makaleye fotoğraf ekleyin")

    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']         

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content','article_image']

article/views.py
from email import message
from django.http import HttpResponse
from django.shortcuts import redirect, render,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def articles(request):
    keyword=request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains =keyword)
        return render(request,"articles.html",{"articles":articles})  

    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})  

def index(request):
    # return render(request,"index.html")
    if request.user.is_authenticated:
        articles = Article.objects.filter(author=request.user)
        context={"articles":articles}
        return render(request,"dashboard.html",context)  
    else:
        return render(request,"index.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context={"articles":articles}
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        """
        yazar bilgisi belirtilmedi icin hata verir.(sadece form.save() denirse)
        """
        article=form.save(commit=False)
        article.author = request.user
        article.save()


        messages.success(request,"Makale başarıyla oluşturuldu")
        return redirect("index")

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    # article=Article.objects.filter(id=id).first()
    # print(article)
    article=get_object_or_404(Article,id=id)
    comments=article.comments.all()

    return render(request,"detail.html",{"article":article, "comments":comments})

@login_required(login_url = "user:login")
def editarticle(request,id):
    article=get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi")
        return redirect("index")

    return render(request,"edit.html",{"form":form})

@login_required(login_url = "user:login")
def deletearticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale başarıyla silindi.")
    return redirect("article:dashboard")

def about(request):
    return render(request,"about.html")

def addcomment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author=request.POST.get("comment_author")
        comment_content=request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author, comment_content=comment_content)
        newComment.article=article
        newComment.save()

    # return redirect("/articles/article/" + str(id))
    #/articles/detail/id:
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>Burası about sayfasındaki içeriktir. (django)</p>
<hr>
{% endblock %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}



{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6 offset-md-3">

<h3>Makale Ekle</h3>
<hr>

<form method="post" enctype="multipart/form-data">
{% csrf_token%}
{{form.media}}
{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger">Kayıt</button>
</form>

<hr>

</div>
</div>
{% endblock %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="container mt-5">
  <div class="row"> 
    <div class="col-lg-8">
      <h3>Makaleler</h3> 
      <hr>   
    </div>
      
  </div>

{% if articles %}
        {% for article in articles %}
          <div class="row">
              <div class="col-lg-8">
              <!-- Post content-->
                  <article>
                  <!-- Post header-->
                  <header class="mb-4">
                  <!-- Post title-->
                  <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a>
                  <!-- Post meta content-->
                  <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
                  <!-- Post categories
                  <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                  <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a> -->
                  </header>
                  <!-- Preview image figure -->
                  {% if article.article_image %}
                  <figure class="mb-4"><a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="{{article.article_image.url}}" /></a>
                  </figure>
                  {% endif %}
                  <!-- Post content safe : html içerikleri doğru sekilde göstermek icin
                  truncatewords:10 ilk 10 karakteri gösteriyor
                  -->                
                  <p class="lead">
                  {{article.content|safe|truncatewords:10}}
                  </p>
                  <a style="float:right" href="/articles/article/{{article.id}}" class="btn btn-warning">Devamını oku</a>
                  </article>
              </div>
          </div>
        {% endfor %} 
</div>

{% else %}
<div class="row"> 
  <div class="col-lg-8">
    <div class="alert alert-danger">Makale Bulunamadı.</div>
    <a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
  </div>    
</div>



{% endif %}



{% endblock %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p> Hoşgeldiniz <small>{{request.user.username}}</small></p>
<hr>



{% if articles %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Tarih</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

        {% for article in articles %}
            <tr>
            <th scope="row">{{ article.id }}</th>
            <td><a href="/articles/article/{{ article.id }}">{{ article.title }}</a></td>
            <td>{{ article.author }}</td>
            <td>{{ article.created_date }}</td>
            <td><a href="/articles/edit/{{ article.id }}" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/articles/delete/{{ article.id }}" class="btn btn-warning">Sil</a></td>
            </tr>
        {% endfor %}


 
    </tbody>
  </table>






{% else %}
    <div class="alert alert-danger">Henüz makaleniz yok</div>
{% endif %}


<a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
<hr>


{% endblock %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

{% if article %}

<div class="container mt-5">
<div class="row">
    <div class="col-lg-8">
    <!-- Post content-->
        <article>
        <!-- Post header-->
        <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">{{article.title}}</h1>
        <!-- Post meta content-->
        <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
        <!-- Post categories
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a> -->
        </header>
        <!-- Preview image figure -->
        {% if article.article_image %}
        <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="{{article.article_image.url}}" /></figure>
        {% endif %}
        <!-- Post content-->                
        <p class="lead">
        {{article.content|safe}}
        </p>                
        </article>
    </div>
</div>



<div class="card-body">
    {% if comments %}

    {% for comment in comments %}
    <div class="media mb-4">
        <div class="d-flex mr-3"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
        <div class="media-body">
            <div class="media-body">{{ comment.comment_author }} | {{ comment.comment_date }}</div>
            {{ comment.comment_content }}
        </div>
    </div>
    {% endfor  %}

    {% else %}
    <div class="alert alert-danger">
    Bu makaleye hiç yorum yapılmamış, ilk yorumu siz yapın.
    </div>
    {% endif %}
</div>


<div class="card my-4">
    <div class="card-body">
        <!-- Comment form-->
        <h5 class="card-header">Yorum Ekle</h5>
        <form method="post" action="{% url 'article:comment' article.id %}"> <!--- /articles/comment/{{article.id}} -->
            {% csrf_token %}
            <div class="form-group">
                <label for="comment_author">İsim:</label>
                <input type="text" name="comment_author" class="form-control" id="comment_author" placeholder="İsminiz"></textarea>
            </div>

            <div class="form-group">
                <label for="txtarea">Yorum:</label>
            <textarea name="comment_content" class="form-control" rows="3" placeholder="Yorum ekle!"></textarea>
            </div>
            <button type="submit" class="btn btn-danger">Kaydet</button>
            
        </form>
    </div>
</div>


</div>




{% endif %}
{% endblock %}

templates/edit.html
{% extends "layout.html" %}

{% block body %}



{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6 offset-md-3">

<h3>Makale Güncelle</h3>
<hr>

<form method="post" enctype="multipart/form-data">
{% csrf_token%}
{{form.media}}
{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger">Kayıt</button>
</form>

<hr>

</div>
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block body %}


<div class="jumbotron">
<h3>Yazılım Bilimi DJANGO Bloğuna hoşgeldiniz</h3>

<p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz.</p>
<p>
{% if request.user.is_authenticated %}
    Merhaba {{ request.user.username }}
{% else %}
    Giriş yapılmamış.
{% endif %}
</p>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <title>YB Blog DJANGO</title>
</head>
<body>
    {% include "includes/navbar.html" %}


<div style="margin-top:100px; margin-bottom: 80px;" class="container">

{% if messages %}
    {% for message in messages %}

        {% if message.tags == "error" %}
        <div class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}

    {% endfor %}
{% endif %}


{% block body %}

{% endblock %}
</div>


    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6 offset-md-3">



<h3>Giriş</h3>
<hr>

<form method="post">
{% csrf_token%}
{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger">Giriş</button>
</form>

<hr>

</div>
</div>
{% endblock %}

templates/logout.html
{% extends "layout.html" %}

{% block body %}
<h3>Çıkış</h3>
<hr>
<p>Burası register sayfasındaki içeriktir. (django)</p>
<hr>
{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt ol</h3>
        <div class="container">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Kayıt</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}